### ISSUE TITLE
Stepper wire management is hindered by endstop placement

### ISSUE THREAD

**Issue by brendanjerwin** [JohnSL/3DR-Simple-Delta-Printer#2]
The port to pass the stepper wires under the top of the printer is on the same side as the endstop mount. This makes routing those wires a bit tough as you have to squeeze them between the gap left by the endstop mount.

Moving the endstop mount just to the other side should provide the same functionality without hindering wire management.

![image](https://f.cloud.github.com/assets/3039/1981671/14f094e8-83e2-11e3-8fb2-7e89c2630360.png)

**Comment by JohnSL** [comment]
I've added a second slot on the other side, so you can route the wires either way, depending on which routing works better. I've uploaded these changes.
