### ISSUE TITLE
Integrate screw "towers" with walls for more strength

### ISSUE THREAD

**Issue by brendanjerwin** [JohnSL/3DR-Simple-Delta-Printer#4]
The screw towers that hold the electronics seem like they are potentially fragile. The print such that sheering forces would be applied to the layer bonds, running the risk of delamination.

They are awfully close to the walls already. It seems some extra material could be added to join them with the walls directly.

![image](https://f.cloud.github.com/assets/3039/1981689/fed273d8-83e2-11e3-9274-690b823c3a50.png)

**Comment by JohnSL** [comment]
I've added fillets to the wings. The new parts are now uploaded (SolidWorks, STL, and STEP).
